apiVersion: v1
kind: Namespace
metadata:
  name: ticketing
  labels:
    name: ticketing
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: ticketing-dev
  labels:
    name: ticketing-dev
    environment: development
