apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service
  namespace: ticketing
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ticketing-inventory-service-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: booking-service
  namespace: ticketing
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ticketing-booking-service-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-service
  namespace: ticketing
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ticketing-events-service-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: ticketing
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ticketing-auth-service-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: search-service
  namespace: ticketing
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ticketing-search-service-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service
  namespace: ticketing
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ticketing-payment-service-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: ticketing
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ticketing-notification-service-role
